# Site wide configuration

title:            keiser lab @ ucsf
locale:           en_US
url:              http://www.keiserlab.org
#url:              http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Michael Keiser
  avatar: bio-photo.jpg
<<<<<<< 08dbf6153bd461fb19c768bb1c7e2768c90543e8
  bio: "Describe your self."
  email:
  disqus-shortname:
=======
  bio: ""
  email: keiser@keiserlab.org
  disqus-shortname: 
>>>>>>> set default site config and owner
  twitter: #username
  facebook: #username
  google:
    plus: #username
<<<<<<< 08dbf6153bd461fb19c768bb1c7e2768c90543e8
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: #username
  xing: #username
=======
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: mjke
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: keiser
>>>>>>> set default site config and owner
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
